ZSH_HOME="$HOME/.zsh"
source $ZSH_HOME/path.zsh

# SSHで接続した先で日本語が使えるようにする
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# ScalaのREPLで日本語を使えるようにする
export JAVA_OPTS="-Dfile.encoding=UTF-8"

# エディタ
export EDITOR=/usr/local/bin/vim

# ページャ
export PAGER=/usr/local/bin/vimpager
export MANPAGER=/usr/local/bin/vimpager

# source /open/craftsman-aws/awscli.sh

# go
export GOPATH=/Users/suin/go:/open/golang

# docker-compose
export COMPOSE_FILE=docker-compose.development.yml

export GIT_FORGOT_DIR="$HOME/Dropbox/open/* $HOME/Dropbox/projects/*"
