# SSHで接続した先で日本語が使えるようにする
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# ScalaのREPLで日本語を使えるようにする
export JAVA_OPTS="-Dfile.encoding=UTF-8"

# エディタ
export EDITOR=/usr/local/bin/vim

# ページャ
export PAGER=/usr/local/bin/vimpager
export MANPAGER=/usr/local/bin/vimpager

source /open/craftsman-aws/awscli.sh

# go
export GOPATH=/Users/suin/go

# Homebrew cask でインストールしたAtom用
export ATOM_PATH=~/Applications

# boot2docker
export DOCKER_HOST=tcp://127.0.0.1:2375

# VMWareFusionのイメージを.vagrantの中に作らないようにする
export VAGRANT_VMWARE_CLONE_DIRECTORY=/suin/vagrant-vmware-images
