: "Options" && {
  autoload -U compinit && compinit # 補完機能の強化
  setopt correct # 入力しているコマンド名が間違っている場合にもしかして：を出す。
  setopt nobeep # ビープを鳴らさない
  setopt prompt_subst # 色を使う
  setopt ignoreeof # ^Dでログアウトしない。
  setopt no_tify # バックグラウンドジョブが終了したらすぐに知らせる。
  setopt hist_ignore_dups # 直前と同じコマンドをヒストリに追加しない
  unsetopt auto_menu # タブによるファイルの順番切り替えをしない
  setopt auto_pushd # cd -[tab]で過去のディレクトリにひとっ飛びできるようにする
  setopt auto_cd # ディレクトリ名を入力するだけでcdできるようにする
}

: "Aliases" && {
  alias ls="ls -G" # color for darwin
  alias l="ls -la"
  alias la="ls -la"
  alias l1="ls -1"
  alias tree="tree -NC" # N: 文字化け対策, C:色をつける
  alias cot="open -a CotEditor"
}

: "Key bindings" && {
  bindkey -e # emacs キーマップを選択
  function dig-directory() { cd .. && zle reset-prompt }
  zle -N dig-directory
  bindkey '^K' dig-directory # Ctrl-Kで上のディレクトリに上がる
  bindkey "^R" history-incremental-search-backward
}

: "Plugins" && {
  export ZPLUG_HOME=/usr/local/opt/zplug
  source $ZPLUG_HOME/init.zsh
  zplug "mafredri/zsh-async" # "sindresorhus/pure"が依存している
  zplug "sindresorhus/pure", use:pure.zsh, as:theme # Pretty, minimal and fast ZSH prompt. https://github.com/sindresorhus/pure
  zplug "zsh-users/zsh-syntax-highlighting", defer:2 # Fish shell-like like syntax highlighting for Zsh. https://github.com/zsh-users/zsh-syntax-highlighting
  zplug "supercrabtree/k" # Directory listings for zsh with git features. https://github.com/supercrabtree/k
  zplug check || zplug install
  zplug load
}

: "Misc" && {
  function chpwd() { tree -L 1 } # cdしたあとで、ファイルを表示する
}
